# Generated by Django 3.0.6 on 2020-05-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='review_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
