# Generated by Django 3.0.6 on 2020-05-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_userreview_review_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='review_body',
            field=models.TextField(max_length=500),
        ),
    ]
