# Generated by Django 3.0.6 on 2020-05-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20200518_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreview',
            old_name='review_slug',
            new_name='slug',
        ),
    ]
