# Generated by Django 3.0.6 on 2020-05-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20200518_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='id',
        ),
        migrations.AlterField(
            model_name='userreview',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
